### ISSUE TITLE
Hive Documentation

### ISSUE THREAD

**Issue by simc** [ykaito21/note_app#1]
I really like your app and how you use Hive and wanted to ask you if I may use some of your code for the new Hive documentation (https://newdocs.hivedb.dev) or if you would even be willing to write a guide like [this one](https://newdocs.hivedb.dev/#/tutorials/favorite_books).

Great job!

**Comment by ykaito21** [comment]
I have no problem with using my code if you want. This is the first time to use hive, so I don't have enough knowledge to write a guide.

Thank you for your comment and hard work for building such a nice package!

**Comment by simc** [comment]
Cool, thank you!
